[package]
name = "rust_windows_shellcode"
version = "0.1.0"
authors = ["b1tg <b1tg@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.3.0"
anyhow = "1.0.34"
iced-x86 = "1.10.0"
